<?php

namespace AppBundle\Repository;

/**
 * BestelArtikelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestelArtikelRepository extends \Doctrine\ORM\EntityRepository
{
}
