<?php

namespace AppBundle\Repository;

/**
 * bestelformulierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bestelformulierRepository extends \Doctrine\ORM\EntityRepository
{
}
