<?php

namespace AppBundle\Repository;

/**
 * BestelformulierProductenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestelformulierProductenRepository extends \Doctrine\ORM\EntityRepository
{
}
