<?php

namespace AppBundle\Repository;

/**
 * MagazijnlocatieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazijnlocatieRepository extends \Doctrine\ORM\EntityRepository
{
}
