<?php

namespace AppBundle\Repository;

/**
 * OntvnagstenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntvnagstenRepository extends \Doctrine\ORM\EntityRepository
{
}
