<?php

namespace AppBundle\Repository;

/**
 * ProductTypenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypenRepository extends \Doctrine\ORM\EntityRepository
{
}
