<?php

namespace AppBundle\Repository;

/**
 * RetourenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetourenRepository extends \Doctrine\ORM\EntityRepository
{
}
