<?php

namespace AppBundle\Repository;

/**
 * tempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tempRepository extends \Doctrine\ORM\EntityRepository
{
}
